### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by oferRounds** [Buglife/buglife-android#52] opened 2019-02-20 07:54 UTC
See more info here: http://crashes.to/s/c4ec0bcd1b7

**Comment by schukin** [comment] 2019-02-22 21:44
This appears to be caused by React Native, so closing this and re-opened here: https://github.com/Buglife/react-native-buglife/issues/16

**Closed as completed by schukin** 2019-02-22 21:44 UTC

**Comment by oferRounds** [comment] 2019-02-22 21:59
Cool :)
