### ISSUE TITLE
jsonObjectRequest error launching app

### ISSUE THREAD

**Issue by samrombswm** [Buglife/buglife-android#47] opened 2018-10-24 16:07 UTC
Hello I have tried version 1.3.2 and am getting this error when launching the app.

```
2018-10-23 16:37:31.465 11785-11785/com.example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example, PID: 11785
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/volley/toolbox/JsonObjectRequest;
        at com.buglife.sdk.reporting.ClientEventReporter.reportClientEvent(ClientEventReporter.java:90)
        at com.buglife.sdk.Client$1.run(Client.java:94)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.volley.toolbox.JsonObjectRequest" on path: DexPathList[[zip file "/data/app/com.example-iSGNi6sfxY_UN-gP7fDL5A==/base.apk"],nativeLibraryDirectories=[/data/app/com.example-iSGNi6sfxY_UN-gP7fDL5A==/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.buglife.sdk.reporting.ClientEventReporter.reportClientEvent(ClientEventReporter.java:90) 
        at com.buglife.sdk.Client$1.run(Client.java:94) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

**Comment by schukin** [comment] 2018-10-24 16:48
@samrombswm - yowza. 😬 We're looking into this right now, should have an update for you within a few hours. Apologies for the road bumps, and thanks for reporting this.

**Comment by schukin** [comment] 2018-10-24 18:49
Alright, so this appears to be caused by a missing Volley dependency, which we changed to an `api` dependency internally a while ago to properly support React Native.

We're still figuring out the "right" way to properly fix this while maintaining RN support, but in the meantime you can work around this by adding the Volley dependency explicitly to your `build.gradle`:

```
implementation 'com.android.volley:volley:1.1.0'
```

I'll update this thread shortly once we have a permanent fix in place. Thanks again, and sorry for the trouble!

**Comment by schukin** [comment] 2018-10-25 18:13
Just a quick update here - we're still chugging away at figuring out a perma-fix here, since having to explicitly add Buglife's dependencies admittedly sucks.

This has been an existing issue on & off (depends on things like build environment, etc), but we've done a shit job of documenting it. I've gone ahead and updated the README to include steps to add Volley, since it's inexcusable that the basic integration steps would lead to a crash on launch. Goal is to have this here only temporarily, and we're aiming to have a new build that removes the need to explicitly import Volley asap.

I've created a new ticket (#48) to track the progress of removing Volley; since this crasher is effectively removed with the updated integration steps, I'm going to close this ticket, and refer to this conversation from #48. This is our top priority at the moment, and we should have an update within the next day or two. Thanks again @samrombswm.

**Closed as completed by schukin** 2018-10-25 18:13 UTC
