### ISSUE TITLE
App Crashes when shaking device

### ISSUE THREAD

**Issue by oferRounds** [Buglife/buglife-android#26] opened 2018-02-19 14:10 UTC
http://crashes.to/s/df6536c6718

**Comment by schukin** [comment] 2018-02-21 03:30
Ofer - Can you share a stack trace? We're able to view that Crashlytics link, but unfortunately it doesn't tell us anything other than # of occurrences and device type. :(

**Comment by oferRounds** [comment] 2018-02-21 07:26
Strange! Not sure why it’s not showing the stack trace, I’ve made it public. Anyhow, I attached a screenshot:

<img width="1169" alt="screen shot 2018-02-21 at 9 25 40" src="https://user-images.githubusercontent.com/1477963/36467836-4e10a652-16e9-11e8-9c84-5d756daff5d5.png">

**Comment by danhd123** [comment] 2018-02-21 21:40
Hi Ofer, it looks like you're using an old version of Buglife. Would you mind updating to 1.2.4 and seeing if the problem still occurs?

Also can you check your logs for a line that looks like this:
`W/View: View too large to fit into drawing cache, needs 19324704 bytes, only 16384000 available`

**Comment by schukin** [comment] 2018-10-28 19:04
Closing this issue because we've still been unable to reproduce it. @oferRounds please feel free to re-open or comment if you're either still encountering this issue, or have any additional information to share. Thanks!

**Closed as completed by schukin** 2018-10-28 19:04 UTC
